### ISSUE TITLE
No module found for 'ApplicationServices.Swift' with Python3 on macOS 12 Monterey

### ISSUE THREAD

**Issue by yuleyl** [ronaldoussoren/pyobjc#378] opened 2021-08-13 05:05 UTC

**Comment by ronaldoussoren** [comment] 2021-08-13 08:44
Could you provide more information?  There is no ApplicationServices.Swift module.  Do you get an error about this when importing a PyObjC module/package?

Also:
- Which Python version?
- Which PyObjC version?

**Comment by ronaldoussoren** [comment] 2021-08-14 08:16
There are no references to ApplicationServices.Swift in the PyObjC sources.

I will close this issue unless you provide more information that I can use to reproduce.

**Comment by ronaldoussoren** [comment] 2021-08-15 10:10
I can reproduce the issue with top of the tree:

```
>>> from ApplicationServices import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ApplicationServices.Swift'
```

**Closed** 2021-08-15 10:24 UTC
Labels: bug

**Comment by ronaldoussoren** [comment] 2021-08-15 10:27
Thanks for your report. The issue will be fixed in the 8.0 release.

In general I advise to avoid star imports (e.g. ``from Framework import *`` because framework bindings expose a lot of names and that causes those imports to be close. Just importing what you need tends to be a lot faster, and is also easier
when using code quality tools like flake8.
