### ISSUE TITLE
How I can get access to UIScreen from PyObjC?

### ISSUE THREAD

**Issue by Alexandro1112** [ronaldoussoren/pyobjc#556] opened 2023-05-22 16:14 UTC
**Describe the bug**
I should  to finish my python project using ```PyObjC``` But I understood, what I need ```UIScreen``` class for more stable work some methods.Can I get access ```UIKit``` framework through PyObjC?

**Comment by ronaldoussoren** [comment] 2023-05-23 20:07
This is a duplicate of #352. 

In short: no, accessing UIKit through PyObjC is not possible at this time. The reason for that is that classic macOS binaries cannot load Catalyst libraries like UIKit. Therefore accessing UIKit first requires working on a catalyst build of Python.

**Comment by ronaldoussoren** [comment] 2023-05-25 09:45
> Is it problem with encoding?

No, it is a problem with binary "flavours" on macOS.  Basically there are three kinds of binaries you can run on macOS at the moment:

1. "classic" macOS binaries using AppKit
2. "catalyst" binaries, which are macOS binaries using UIKit (and other iOS frameworks)
3. (on Apple Silicon) iPadOS binaries

The latter are not interesting for this discussion.  A technical limitation on macOS is that binaries from the first category cannot load frameworks from the second, although it is possible to load frameworks from the first catagory from binaries from the second.  

That is, a "catalyst" binary can load a plugin using AppKit, but a binary using AppKit cannot load a plugin using UIKit. 

This is a problem for accessing UIKit using PyObjC because all regular Python builds (Python.org installer, anaconda, homebrew, ...) are in the first category en therefore cannot use UIKit at all.  

The solution for this likely is to create a build of Python using the "catalyst" format, and then port PyObjC to that (which should be easy enough...). I've filed an issue with CPython for Catalyst support, but I don't know when I'll have time to seriously look into this. What worries me a little about a Catalyst Python binary is that this could fracture the community, with some wheels supporting the current build and others supporting a Catalyst build, and because of that working on a Catalyst build does not just mean tweaking the build process to create a Catalyst binary but also means looking into compatibility issues (e.g., could we switch to Catalyst for Python 3.13 as the default format without breaking existing workflows, or ....)

If this were easy I'd already have done so to access the HomeKit framework on macOS (which is available through Catalyst, but not to regular binaries).

**Closed by ronaldoussoren** 2023-05-25 09:45 UTC
Labels: enhancement

**Comment by Alexandro1112** [comment] 2023-05-25 10:37
Fine.Thaks for large answer.Uikit does not support mac using.Right?

**Comment by ronaldoussoren** [comment] 2023-05-25 12:50
> Fine.Thaks for large answer.Uikit does not support mac using.Right?

Catalyst is also Mac, but different than normal Mac binaries, and to be honest I don't know why.

> And the last.Why is there no IOKit framework in Pyobjc?

Because I haven't had time yet to work on this. The IOKit library is pretty low-level and seems to require significant work to create usable bindings.  I haven't worked on this because I don't have a clear use case myself and haven't seen compelling use cases from others.
