### ISSUE TITLE
framework-wrappers.rst file not rendered correctly

### ISSUE THREAD

**Issue by yasoob** [ronaldoussoren/pyobjc#517] opened 2022-12-14 11:43 UTC
The [`framework-wrappers.rst`](https://github.com/ronaldoussoren/pyobjc/blob/e3771a7777a85eaea569885e17581ca5ef41e2ae/docs/notes/framework-wrappers.rst) file is not rendered correctly on GitHub. It contains a table that is not visible on GitHub. The displayed version looks like this:

![image](https://user-images.githubusercontent.com/3696393/207585943-50b91931-2ffb-4eac-ad0c-ed3992c6c798.png)

Whereas the raw version also contains a table:
![image](https://user-images.githubusercontent.com/3696393/207586035-d4198ff8-39b3-43e7-95ad-173d5fcb5a86.png)

I am not sure if this issue is caused by some erroneous markup in the `rst` file or if this is a bug with GitHub.

**Comment by ronaldoussoren** [comment] 2022-12-14 12:28
Thanks. This is caused by a problem in the markup. I have a fix for this, but haven't merged that into the master branch yet. 

See https://github.com/ronaldoussoren/pyobjc/blob/selector-transform-in-python-gh306/docs/notes/framework-wrappers.rst.

**Closed** 2022-12-16 16:17 UTC
Labels: bug
