### ISSUE TITLE
IBActions doesn't always update the View

### ISSUE THREAD

**Issue by acaland** [ronaldoussoren/pyobjc#396] opened 2021-11-02 15:54 UTC
Hello,

I was starting to experiment with PyObjc and I noticed a strange behaviour: clicking on UI controls not always update the view. For example, I have tried the TableModel example and when I double click on a row the IBaction method is fired correctly but the row itself on TableView doesn't. I have also tried with a simple btnClick and the button is not shown as pressed even if the event handler is called. I have tried both 7.3 and 8.0b1 on MacOS High Sierra, Big Sur and Monterey.

You can see this behaviour in the following video:

https://user-images.githubusercontent.com/3988594/139886664-e7f40fae-494c-4757-9f68-8564b34afba6.mov

thanks

**Comment by ronaldoussoren** [comment] 2021-11-15 19:58
That's weird. What version of Python do you use?

**Comment by acaland** [comment] 2021-11-16 09:52
Sorry, I forgot to add the details related to my dev environment. I am on Big Sur 11.6.1 and use Python 3.9.7. I installed the latest PyObj 8.0b1

Thanks

```
(.py_env) acaland@iMac PyObjCExample-TableModel % python
Python 3.9.7 (default, Oct 13 2021, 06:45:31) 
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
```

**Comment by ronaldoussoren** [comment] 2021-11-23 09:48
I can reproduce this on my machine (Python 3.97, macOS 12, PyObjC 8.0.1b1).

That said, this isn't a problem if you're using the example in ``pyobjc-framework-Cocoa/Examples/AppKit/TableModel``, the implementation of "tableView_shouldSelectRow_" in that example (line 70) only allows selecting every other row.

**Comment by ronaldoussoren** [comment] 2021-11-24 12:58
I'm closing this issue because the behaviour is consistent with the code in the TableModel example in the Cocoa bindings, that example only allows selecting every other row (that is pretty useless behaviour, but does show how to use the API)

**Closed by ronaldoussoren** 2021-11-24 12:58 UTC

**Comment by acaland** [comment] 2021-11-24 16:55
Thank you @ronaldoussoren and sorry about that: I didn't take a careful look at the code example. I was also fooled  by a similar behaviour in the HelloWorld.py example, where clicking on a NSButton with attached a NSSound didn't always trigger the reproduction, but I was clicking too fast and the attached audio file, having a  length of 1 sec, had to complete the playing before the button could handle another click event. Thank you again

**Comment by ronaldoussoren** [comment] 2021-11-25 09:42
Glad I could help. And you weren't the only one confused by this, at first I thought this was a real bug.
